// Статьи справки по встроенным функциям. Двуязычные (RU/EN), с примером
// и примечанием об ошибках. Сгенерировано из calc-core (см. scripts).
// Проверяется тестами в help.rs: каждое имя реестра имеет статью,
// категория известна, пример вычисляется без ошибки.
#[rustfmt::skip]
static ENTRIES: &[HelpEntry] = &[
    HelpEntry {
        name: "Abs",
        category: "math",
        signature: "Abs(x)",
        summary_ru: "Возвращает абсолютное значение числа, сохраняя тип (целое для Int, дробное для Float).",
        summary_en: "Returns the absolute value of a number, preserving its type (Int stays Int, Float stays Float).",
        example: "Abs(-3)",
        note_ru: "Ошибка переполнения при Abs(i128::MIN).",
        note_en: "Overflow error for Abs of i128::MIN.",
    },
    HelpEntry {
        name: "Adler32",
        category: "hash",
        signature: "Adler32(s)",
        summary_ru: "Возвращает контрольную сумму Adler-32 строки в виде 8-символьной hex-строки.",
        summary_en: "Returns the Adler-32 checksum of a string as an 8-character hex string.",
        example: "Adler32(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "And",
        category: "logic",
        signature: "And(a, b)",
        summary_ru: "Возвращает побитовое И двух целых чисел.",
        summary_en: "Returns the bitwise AND of two integers.",
        example: "And(12, 10)",
        note_ru: "Аргументы должны приводиться к целому.",
        note_en: "Arguments must coerce to integers.",
    },
    HelpEntry {
        name: "AppendFile",
        category: "fileio",
        signature: "AppendFile(path, data)",
        summary_ru: "Дописывает строку data в конец файла path (создаёт файл при отсутствии) и возвращает записанную строку.",
        summary_en: "Appends the string data to the end of file path (creating it if absent) and returns the written string.",
        example: "AppendFile(\"log.txt\", \"line\\n\")",
        note_ru: "Обращается к файловой системе; ошибка ввода-вывода при недоступности пути.",
        note_en: "Touches the filesystem; I/O error if the path is not writable.",
    },
    HelpEntry {
        name: "ArcCos",
        category: "trig",
        signature: "ArcCos(x)",
        summary_ru: "Возвращает арккосинус x в радианах.",
        summary_en: "Returns the arccosine of x in radians.",
        example: "ArcCos(0.5)",
        note_ru: "Для |x|>1 результат NaN.",
        note_en: "Returns NaN for |x|>1.",
    },
    HelpEntry {
        name: "ArcCosH",
        category: "trig",
        signature: "ArcCosH(x)",
        summary_ru: "Возвращает гиперболический ареакосинус x.",
        summary_en: "Returns the inverse hyperbolic cosine of x.",
        example: "ArcCosH(2)",
        note_ru: "Для x<1 результат NaN.",
        note_en: "Returns NaN for x<1.",
    },
    HelpEntry {
        name: "ArcSin",
        category: "trig",
        signature: "ArcSin(x)",
        summary_ru: "Возвращает арксинус x в радианах.",
        summary_en: "Returns the arcsine of x in radians.",
        example: "ArcSin(1)",
        note_ru: "Для |x|>1 результат NaN.",
        note_en: "Returns NaN for |x|>1.",
    },
    HelpEntry {
        name: "ArcSinH",
        category: "trig",
        signature: "ArcSinH(x)",
        summary_ru: "Возвращает гиперболический ареасинус x.",
        summary_en: "Returns the inverse hyperbolic sine of x.",
        example: "ArcSinH(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "ArcTan",
        category: "trig",
        signature: "ArcTan(x)",
        summary_ru: "Возвращает арктангенс x в радианах.",
        summary_en: "Returns the arctangent of x in radians.",
        example: "ArcTan(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "ArcTanH",
        category: "trig",
        signature: "ArcTanH(x)",
        summary_ru: "Возвращает гиперболический ареатангенс x.",
        summary_en: "Returns the inverse hyperbolic tangent of x.",
        example: "ArcTanH(0.5)",
        note_ru: "Для |x|>=1 результат ±бесконечность или NaN.",
        note_en: "Returns ±infinity or NaN for |x|>=1.",
    },
    HelpEntry {
        name: "BaseToInt",
        category: "bases",
        signature: "BaseToInt(s, base)",
        summary_ru: "Разбирает строку s как число в системе счисления base (2..=36) и возвращает целое; ведущий '-' допускается.",
        summary_en: "Parses string s as a number in the given base (2..=36) and returns the integer; a leading '-' is allowed.",
        example: "BaseToInt(\"FF\", 16)",
        note_ru: "Ошибка при base вне 2..=36, пустой строке, недопустимой цифре или переполнении.",
        note_en: "Errors on base outside 2..=36, empty string, invalid digit, or overflow.",
    },
    HelpEntry {
        name: "BinToInt",
        category: "bases",
        signature: "BinToInt(s)",
        summary_ru: "Разбирает двоичную строку s и возвращает целое число.",
        summary_en: "Parses a binary string s and returns the integer.",
        example: "BinToInt(\"1010\")",
        note_ru: "Ошибка при недопустимой цифре или пустой строке.",
        note_en: "Errors on an invalid digit or empty string.",
    },
    HelpEntry {
        name: "BitClear",
        category: "bits",
        signature: "BitClear(v, n)",
        summary_ru: "Возвращает v со сброшенным (обнулённым) битом номер n.",
        summary_en: "Returns v with bit number n cleared (set to 0).",
        example: "BitClear(8, 3)",
        note_ru: "Индекс бита n должен быть в диапазоне 0..=127.",
        note_en: "Bit index n must be in the range 0..=127.",
    },
    HelpEntry {
        name: "BitSet",
        category: "bits",
        signature: "BitSet(v, n)",
        summary_ru: "Возвращает v с установленным (в 1) битом номер n.",
        summary_en: "Returns v with bit number n set to 1.",
        example: "BitSet(0, 3)",
        note_ru: "Индекс бита n должен быть в диапазоне 0..=127.",
        note_en: "Bit index n must be in the range 0..=127.",
    },
    HelpEntry {
        name: "BitTest",
        category: "bits",
        signature: "BitTest(v, n)",
        summary_ru: "Возвращает булево значение: установлен ли бит номер n в v.",
        summary_en: "Returns a boolean indicating whether bit number n of v is set.",
        example: "BitTest(8, 3)",
        note_ru: "Индекс бита n должен быть в диапазоне 0..=127.",
        note_en: "Bit index n must be in the range 0..=127.",
    },
    HelpEntry {
        name: "BitToggle",
        category: "bits",
        signature: "BitToggle(v, n)",
        summary_ru: "Возвращает v с инвертированным битом номер n.",
        summary_en: "Returns v with bit number n toggled.",
        example: "BitToggle(0, 3)",
        note_ru: "Индекс бита n должен быть в диапазоне 0..=127.",
        note_en: "Bit index n must be in the range 0..=127.",
    },
    HelpEntry {
        name: "Ceil",
        category: "math",
        signature: "Ceil(x)",
        summary_ru: "Возвращает наименьшее целое, не меньшее x (округление вверх).",
        summary_en: "Returns the smallest integer not less than x (round up).",
        example: "Ceil(2.1)",
        note_ru: "Ошибка, если результат выходит за пределы i128.",
        note_en: "Errors if the result falls outside the i128 range.",
    },
    HelpEntry {
        name: "Chr",
        category: "strings",
        signature: "Chr(n)",
        summary_ru: "Возвращает строку из одного символа Unicode с кодовой точкой n.",
        summary_en: "Returns a one-character string for the Unicode code point n.",
        example: "Chr(65)",
        note_ru: "Ошибка при n<0, n>U+10FFFF или недопустимой кодовой точке (суррогаты).",
        note_en: "Errors for n<0, n>U+10FFFF, or an invalid code point (surrogates).",
    },
    HelpEntry {
        name: "Compare",
        category: "strings",
        signature: "Compare(a, b)",
        summary_ru: "Лексикографически сравнивает две строки, возвращая -1, 0 или 1.",
        summary_en: "Lexicographically compares two strings, returning -1, 0, or 1.",
        example: "Compare(\"apple\", \"banana\")",
        note_ru: "Сравнение побайтовое (по значениям Unicode-скаляров), регистрозависимое.",
        note_en: "Comparison is byte-wise (by Unicode scalar values) and case-sensitive.",
    },
    HelpEntry {
        name: "Concat",
        category: "strings",
        signature: "Concat(s1, s2, ...)",
        summary_ru: "Склеивает все строковые аргументы в одну строку.",
        summary_en: "Concatenates all string arguments into a single string.",
        example: "Concat(\"a\", \"b\", \"c\")",
        note_ru: "Требует минимум 1 аргумент; все аргументы должны быть строками.",
        note_en: "Requires at least 1 argument; every argument must be a string.",
    },
    HelpEntry {
        name: "Copy",
        category: "strings",
        signature: "Copy(s, start, len)",
        summary_ru: "Возвращает подстроку из s длиной len символов, начиная с позиции start (1-based, по символам).",
        summary_en: "Returns a substring of s of len characters starting at position start (1-based, character-indexed).",
        example: "Copy(\"abcdef\", 2, 3)",
        note_ru: "start должен быть >=1, len >=0; выход за конец строки усекается, start за концом даёт пустую строку.",
        note_en: "start must be >=1 and len >=0; length is clamped at the end, and a start past the end yields an empty string.",
    },
    HelpEntry {
        name: "Cos",
        category: "trig",
        signature: "Cos(x)",
        summary_ru: "Возвращает косинус угла x, заданного в радианах.",
        summary_en: "Returns the cosine of angle x given in radians.",
        example: "Cos(0)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "CosH",
        category: "trig",
        signature: "CosH(x)",
        summary_ru: "Возвращает гиперболический косинус x.",
        summary_en: "Returns the hyperbolic cosine of x.",
        example: "CosH(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Cotan",
        category: "trig",
        signature: "Cotan(x)",
        summary_ru: "Возвращает котангенс угла x в радианах (1/tan(x)).",
        summary_en: "Returns the cotangent of angle x in radians (1/tan(x)).",
        example: "Cotan(1)",
        note_ru: "Для x, кратного π, результат ±бесконечность.",
        note_en: "Returns ±infinity for x that is a multiple of π.",
    },
    HelpEntry {
        name: "Crc32",
        category: "hash",
        signature: "Crc32(s)",
        summary_ru: "Возвращает контрольную сумму CRC-32 строки в виде 8-символьной hex-строки.",
        summary_en: "Returns the CRC-32 checksum of a string as an 8-character hex string.",
        example: "Crc32(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Decrypt",
        category: "cipher",
        signature: "Decrypt(alg, key, ciphertext)",
        summary_ru: "Расшифровывает hex-шифротекст алгоритмом AES-CBC (alg \"aes\"/\"rijndael\") с hex-ключом key и нулевым IV, возвращая исходную UTF-8 строку.",
        summary_en: "Decrypts a hex ciphertext using AES-CBC (alg \"aes\"/\"rijndael\") with the hex key and a zero IV, returning the original UTF-8 string.",
        example: "Decrypt(\"aes\", \"000102030405060708090a0b0c0d0e0f\", \"9276fdf384f38518fa6c8310f191678d\")",
        note_ru: "Ключ hex длиной 16/24/32 байта; ошибка при неверном ключе, hex, padding или невалидном UTF-8.",
        note_en: "Key is hex of 16/24/32 bytes; errors on bad key, hex, padding, or non-UTF-8 result.",
    },
    HelpEntry {
        name: "DegToRad",
        category: "trig",
        signature: "DegToRad(x)",
        summary_ru: "Переводит угол x из градусов в радианы.",
        summary_en: "Converts angle x from degrees to radians.",
        example: "DegToRad(180)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "E",
        category: "math",
        signature: "E()",
        summary_ru: "Возвращает математическую константу e (основание натурального логарифма).",
        summary_en: "Returns the mathematical constant e (base of the natural logarithm).",
        example: "E()",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Encrypt",
        category: "cipher",
        signature: "Encrypt(alg, key, plaintext)",
        summary_ru: "Шифрует строку plaintext алгоритмом AES-CBC (alg \"aes\"/\"rijndael\") с hex-ключом key, нулевым IV и PKCS7, возвращая hex-шифротекст.",
        summary_en: "Encrypts plaintext using AES-CBC (alg \"aes\"/\"rijndael\") with the hex key, a zero IV, and PKCS7 padding, returning a hex ciphertext.",
        example: "Encrypt(\"aes\", \"000102030405060708090a0b0c0d0e0f\", \"hello world\")",
        note_ru: "Фиксированный нулевой IV — детерминированно, но небезопасно; ключ hex длиной 16/24/32 байта.",
        note_en: "Fixed zero IV — deterministic but not secure; key is hex of 16/24/32 bytes.",
    },
    HelpEntry {
        name: "Exp",
        category: "math",
        signature: "Exp(x)",
        summary_ru: "Возвращает экспоненту e в степени x.",
        summary_en: "Returns e raised to the power x.",
        example: "Exp(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Fact",
        category: "math",
        signature: "Fact(n)",
        summary_ru: "Возвращает факториал целого неотрицательного n.",
        summary_en: "Returns the factorial of a non-negative integer n.",
        example: "Fact(5)",
        note_ru: "Ошибка при n<0 и при переполнении i128 (примерно n>33).",
        note_en: "Errors for n<0 and on i128 overflow (roughly n>33).",
    },
    HelpEntry {
        name: "FileToStr",
        category: "fileio",
        signature: "FileToStr(path)",
        summary_ru: "Читает файл path целиком и возвращает его содержимое как строку.",
        summary_en: "Reads the entire file at path and returns its contents as a string.",
        example: "FileToStr(\"notes.txt\")",
        note_ru: "Обращается к файловой системе; ошибка при отсутствии файла или не-UTF-8 содержимом.",
        note_en: "Touches the filesystem; errors if the file is missing or not valid UTF-8.",
    },
    HelpEntry {
        name: "Floor",
        category: "math",
        signature: "Floor(x)",
        summary_ru: "Возвращает наибольшее целое, не превышающее x (округление вниз).",
        summary_en: "Returns the largest integer not greater than x (round down).",
        example: "Floor(2.7)",
        note_ru: "Ошибка, если результат выходит за пределы i128.",
        note_en: "Errors if the result falls outside the i128 range.",
    },
    HelpEntry {
        name: "FormatFloat",
        category: "strings",
        signature: "FormatFloat(x, digits)",
        summary_ru: "Форматирует число x как строку с фиксированным количеством digits знаков после запятой.",
        summary_en: "Formats number x as a string with a fixed digits decimal places.",
        example: "FormatFloat(3.14159, 2)",
        note_ru: "digits должен быть в диапазоне 0..=100.",
        note_en: "digits must be in the range 0..=100.",
    },
    HelpEntry {
        name: "Frac",
        category: "math",
        signature: "Frac(x)",
        summary_ru: "Возвращает дробную часть x (со знаком x).",
        summary_en: "Returns the fractional part of x (with the sign of x).",
        example: "Frac(2.25)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Gcd",
        category: "math",
        signature: "Gcd(a, b)",
        summary_ru: "Возвращает наибольший общий делитель двух целых чисел (неотрицательный).",
        summary_en: "Returns the greatest common divisor of two integers (non-negative).",
        example: "Gcd(12, 8)",
        note_ru: "Ошибка, если аргумент равен i128::MIN.",
        note_en: "Errors if an argument equals i128::MIN.",
    },
    HelpEntry {
        name: "Hash",
        category: "hash",
        signature: "Hash(alg, s)",
        summary_ru: "Вычисляет хеш строки s алгоритмом alg (md5, sha1, sha224/256/384/512, sha3_256, sha3_512, ripemd160, tiger, crc32, adler32) и возвращает hex-строку.",
        summary_en: "Computes the hash of string s using algorithm alg (md5, sha1, sha224/256/384/512, sha3_256, sha3_512, ripemd160, tiger, crc32, adler32) and returns a hex string.",
        example: "Hash(\"sha256\", \"abc\")",
        note_ru: "Ошибка при неизвестном имени алгоритма (регистр не важен).",
        note_en: "Errors on an unknown algorithm name (case-insensitive).",
    },
    HelpEntry {
        name: "HexToInt",
        category: "bases",
        signature: "HexToInt(s)",
        summary_ru: "Разбирает шестнадцатеричную строку s и возвращает целое число.",
        summary_en: "Parses a hexadecimal string s and returns the integer.",
        example: "HexToInt(\"FF\")",
        note_ru: "Регистр не важен; ошибка при недопустимой цифре, пустой строке или переполнении.",
        note_en: "Case-insensitive; errors on an invalid digit, empty string, or overflow.",
    },
    HelpEntry {
        name: "Hypot",
        category: "math",
        signature: "Hypot(x, y)",
        summary_ru: "Возвращает длину гипотенузы sqrt(x²+y²) без промежуточного переполнения.",
        summary_en: "Returns the hypotenuse length sqrt(x²+y²) without intermediate overflow.",
        example: "Hypot(3, 4)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "IntToBase",
        category: "bases",
        signature: "IntToBase(n, base)",
        summary_ru: "Преобразует целое n в строку в системе счисления base (2..=36); отрицательные числа получают префикс '-'.",
        summary_en: "Converts integer n to a string in the given base (2..=36); negative numbers get a '-' prefix.",
        example: "IntToBase(255, 16)",
        note_ru: "Ошибка при base вне 2..=36; цифры выше 9 — заглавные буквы A..Z.",
        note_en: "Errors on base outside 2..=36; digits above 9 are uppercase letters A..Z.",
    },
    HelpEntry {
        name: "IntToBin",
        category: "bases",
        signature: "IntToBin(n)",
        summary_ru: "Преобразует целое n в двоичную строку.",
        summary_en: "Converts integer n to a binary string.",
        example: "IntToBin(10)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "IntToHex",
        category: "bases",
        signature: "IntToHex(n)",
        summary_ru: "Преобразует целое n в шестнадцатеричную строку (заглавными).",
        summary_en: "Converts integer n to a hexadecimal string (uppercase).",
        example: "IntToHex(255)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "IntToOct",
        category: "bases",
        signature: "IntToOct(n)",
        summary_ru: "Преобразует целое n в восьмеричную строку.",
        summary_en: "Converts integer n to an octal string.",
        example: "IntToOct(8)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "IntToRoman",
        category: "bases",
        signature: "IntToRoman(n)",
        summary_ru: "Преобразует целое n (1..=3999) в строку римскими цифрами.",
        summary_en: "Converts integer n (1..=3999) to a Roman-numeral string.",
        example: "IntToRoman(2024)",
        note_ru: "Ошибка при n вне диапазона 1..=3999.",
        note_en: "Errors for n outside the range 1..=3999.",
    },
    HelpEntry {
        name: "Lcm",
        category: "math",
        signature: "Lcm(a, b)",
        summary_ru: "Возвращает наименьшее общее кратное двух целых чисел (0, если один из них 0).",
        summary_en: "Returns the least common multiple of two integers (0 if either is 0).",
        example: "Lcm(4, 6)",
        note_ru: "Ошибка при i128::MIN или переполнении результата.",
        note_en: "Errors on i128::MIN or when the result overflows.",
    },
    HelpEntry {
        name: "Length",
        category: "strings",
        signature: "Length(s)",
        summary_ru: "Возвращает число символов Unicode в строке s.",
        summary_en: "Returns the number of Unicode characters in string s.",
        example: "Length(\"hello\")",
        note_ru: "Считаются символы (скаляры), а не байты.",
        note_en: "Counts characters (scalars), not bytes.",
    },
    HelpEntry {
        name: "Ln",
        category: "math",
        signature: "Ln(x)",
        summary_ru: "Возвращает натуральный логарифм x.",
        summary_en: "Returns the natural logarithm of x.",
        example: "Ln(E())",
        note_ru: "Для x<0 результат NaN, для x=0 — минус бесконечность.",
        note_en: "Returns NaN for x<0 and negative infinity for x=0.",
    },
    HelpEntry {
        name: "Log",
        category: "math",
        signature: "Log(x, base)",
        summary_ru: "Возвращает логарифм x по основанию base (ln(x)/ln(base)).",
        summary_en: "Returns the logarithm of x to the given base (ln(x)/ln(base)).",
        example: "Log(81, 3)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Log10",
        category: "math",
        signature: "Log10(x)",
        summary_ru: "Возвращает десятичный логарифм x.",
        summary_en: "Returns the base-10 logarithm of x.",
        example: "Log10(1000)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Log2",
        category: "math",
        signature: "Log2(x)",
        summary_ru: "Возвращает двоичный логарифм x.",
        summary_en: "Returns the base-2 logarithm of x.",
        example: "Log2(8)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Lower",
        category: "strings",
        signature: "Lower(s)",
        summary_ru: "Возвращает строку s, приведённую к нижнему регистру.",
        summary_en: "Returns string s converted to lowercase.",
        example: "Lower(\"ABC\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Max",
        category: "math",
        signature: "Max(x1, x2, ...)",
        summary_ru: "Возвращает наибольший из аргументов (по числовому значению), сохраняя исходный тип этого аргумента.",
        summary_en: "Returns the largest of the arguments (by numeric value), preserving that argument's original type.",
        example: "Max(3, 1, 7)",
        note_ru: "Требует минимум 1 аргумент; все аргументы должны быть числами.",
        note_en: "Requires at least 1 argument; all arguments must be numeric.",
    },
    HelpEntry {
        name: "Md5",
        category: "hash",
        signature: "Md5(s)",
        summary_ru: "Возвращает MD5-хеш строки в виде hex-строки.",
        summary_en: "Returns the MD5 hash of a string as a hex string.",
        example: "Md5(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Min",
        category: "math",
        signature: "Min(x1, x2, ...)",
        summary_ru: "Возвращает наименьший из аргументов (по числовому значению), сохраняя исходный тип этого аргумента.",
        summary_en: "Returns the smallest of the arguments (by numeric value), preserving that argument's original type.",
        example: "Min(3, 1, 7)",
        note_ru: "Требует минимум 1 аргумент; все аргументы должны быть числами.",
        note_en: "Requires at least 1 argument; all arguments must be numeric.",
    },
    HelpEntry {
        name: "Not",
        category: "logic",
        signature: "Not(a)",
        summary_ru: "Возвращает побитовое отрицание (дополнение) целого числа.",
        summary_en: "Returns the bitwise NOT (complement) of an integer.",
        example: "Not(0)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Now",
        category: "datetime",
        signature: "Now()",
        summary_ru: "Возвращает текущее время как число секунд с эпохи Unix (float).",
        summary_en: "Returns the current time as seconds since the Unix epoch (float).",
        example: "Now()",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "OctToInt",
        category: "bases",
        signature: "OctToInt(s)",
        summary_ru: "Разбирает восьмеричную строку s и возвращает целое число.",
        summary_en: "Parses an octal string s and returns the integer.",
        example: "OctToInt(\"17\")",
        note_ru: "Ошибка при недопустимой цифре или пустой строке.",
        note_en: "Errors on an invalid digit or empty string.",
    },
    HelpEntry {
        name: "Or",
        category: "logic",
        signature: "Or(a, b)",
        summary_ru: "Возвращает побитовое ИЛИ двух целых чисел.",
        summary_en: "Returns the bitwise OR of two integers.",
        example: "Or(12, 10)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Ord",
        category: "strings",
        signature: "Ord(s)",
        summary_ru: "Возвращает кодовую точку Unicode первого символа строки s.",
        summary_en: "Returns the Unicode code point of the first character of string s.",
        example: "Ord(\"A\")",
        note_ru: "Ошибка при пустой строке.",
        note_en: "Errors on an empty string.",
    },
    HelpEntry {
        name: "Pi",
        category: "math",
        signature: "Pi()",
        summary_ru: "Возвращает математическую константу π.",
        summary_en: "Returns the mathematical constant π.",
        example: "Pi()",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Pos",
        category: "strings",
        signature: "Pos(sub, s)",
        summary_ru: "Возвращает 1-based позицию (по символам) первого вхождения подстроки sub в строку s, либо 0, если не найдено.",
        summary_en: "Returns the 1-based character position of the first occurrence of substring sub in string s, or 0 if not found.",
        example: "Pos(\"cd\", \"abcdef\")",
        note_ru: "Пустая подстрока даёт 0 (как Delphi Pos).",
        note_en: "An empty substring returns 0 (matching Delphi's Pos).",
    },
    HelpEntry {
        name: "Pow",
        category: "math",
        signature: "Pow(base, exp)",
        summary_ru: "Возводит base в степень exp; при целых аргументах с exp>=0 даёт точное целое, иначе — float.",
        summary_en: "Raises base to the power exp; with integer arguments and exp>=0 it yields an exact integer, otherwise a float.",
        example: "Pow(2, 10)",
        note_ru: "Ошибка переполнения при целочисленном результате вне i128.",
        note_en: "Overflow error when an integer result exceeds i128.",
    },
    HelpEntry {
        name: "RadToDeg",
        category: "trig",
        signature: "RadToDeg(x)",
        summary_ru: "Переводит угол x из радиан в градусы.",
        summary_en: "Converts angle x from radians to degrees.",
        example: "RadToDeg(Pi())",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Replace",
        category: "strings",
        signature: "Replace(s, from, to)",
        summary_ru: "Возвращает s со всеми непересекающимися вхождениями подстроки from, заменёнными на to.",
        summary_en: "Returns s with every non-overlapping occurrence of substring from replaced by to.",
        example: "Replace(\"a-b-c\", \"-\", \"+\")",
        note_ru: "Если from пустая, строка возвращается без изменений.",
        note_en: "If from is empty, the string is returned unchanged.",
    },
    HelpEntry {
        name: "Reverse",
        category: "strings",
        signature: "Reverse(s)",
        summary_ru: "Возвращает строку s с символами в обратном порядке.",
        summary_en: "Returns string s with its characters in reverse order.",
        example: "Reverse(\"abc\")",
        note_ru: "Разворот по символам Unicode, а не по байтам.",
        note_en: "Reverses by Unicode characters, not bytes.",
    },
    HelpEntry {
        name: "RipeMD160",
        category: "hash",
        signature: "RipeMD160(s)",
        summary_ru: "Возвращает RIPEMD-160-хеш строки в виде hex-строки.",
        summary_en: "Returns the RIPEMD-160 hash of a string as a hex string.",
        example: "RipeMD160(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "RomanToInt",
        category: "bases",
        signature: "RomanToInt(s)",
        summary_ru: "Разбирает строку римских цифр s и возвращает целое (1..=3999).",
        summary_en: "Parses a Roman-numeral string s and returns the integer (1..=3999).",
        example: "RomanToInt(\"MCMXCIV\")",
        note_ru: "Регистр не важен; ошибка при недопустимом символе или неканонической записи (например IIII).",
        note_en: "Case-insensitive; errors on an invalid character or a non-canonical form (e.g. IIII).",
    },
    HelpEntry {
        name: "Round",
        category: "math",
        signature: "Round(x)",
        summary_ru: "Округляет x до ближайшего целого (половинки — от нуля).",
        summary_en: "Rounds x to the nearest integer (halves away from zero).",
        example: "Round(2.5)",
        note_ru: "Ошибка, если результат выходит за пределы i128.",
        note_en: "Errors if the result falls outside the i128 range.",
    },
    HelpEntry {
        name: "Sha1",
        category: "hash",
        signature: "Sha1(s)",
        summary_ru: "Возвращает SHA-1-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA-1 hash of a string as a hex string.",
        example: "Sha1(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha224",
        category: "hash",
        signature: "Sha224(s)",
        summary_ru: "Возвращает SHA-224-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA-224 hash of a string as a hex string.",
        example: "Sha224(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha256",
        category: "hash",
        signature: "Sha256(s)",
        summary_ru: "Возвращает SHA-256-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA-256 hash of a string as a hex string.",
        example: "Sha256(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha384",
        category: "hash",
        signature: "Sha384(s)",
        summary_ru: "Возвращает SHA-384-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA-384 hash of a string as a hex string.",
        example: "Sha384(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha3_256",
        category: "hash",
        signature: "Sha3_256(s)",
        summary_ru: "Возвращает SHA3-256-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA3-256 hash of a string as a hex string.",
        example: "Sha3_256(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha3_512",
        category: "hash",
        signature: "Sha3_512(s)",
        summary_ru: "Возвращает SHA3-512-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA3-512 hash of a string as a hex string.",
        example: "Sha3_512(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sha512",
        category: "hash",
        signature: "Sha512(s)",
        summary_ru: "Возвращает SHA-512-хеш строки в виде hex-строки.",
        summary_en: "Returns the SHA-512 hash of a string as a hex string.",
        example: "Sha512(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Shl",
        category: "bits",
        signature: "Shl(v, s)",
        summary_ru: "Сдвигает целое v влево на s бит.",
        summary_en: "Shifts integer v left by s bits.",
        example: "Shl(1, 4)",
        note_ru: "Величина сдвига s должна быть в диапазоне 0..=127.",
        note_en: "Shift amount s must be in the range 0..=127.",
    },
    HelpEntry {
        name: "Shr",
        category: "bits",
        signature: "Shr(v, s)",
        summary_ru: "Сдвигает целое v вправо на s бит (арифметически, со знаком).",
        summary_en: "Shifts integer v right by s bits (arithmetic, sign-preserving).",
        example: "Shr(16, 4)",
        note_ru: "Величина сдвига s должна быть в диапазоне 0..=127.",
        note_en: "Shift amount s must be in the range 0..=127.",
    },
    HelpEntry {
        name: "Sign",
        category: "math",
        signature: "Sign(x)",
        summary_ru: "Возвращает знак числа: 1 при x>0, -1 при x<0, 0 при x=0.",
        summary_en: "Returns the sign of a number: 1 if x>0, -1 if x<0, 0 if x=0.",
        example: "Sign(-7)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sin",
        category: "trig",
        signature: "Sin(x)",
        summary_ru: "Возвращает синус угла x, заданного в радианах.",
        summary_en: "Returns the sine of angle x given in radians.",
        example: "Sin(0)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "SinH",
        category: "trig",
        signature: "SinH(x)",
        summary_ru: "Возвращает гиперболический синус x.",
        summary_en: "Returns the hyperbolic sine of x.",
        example: "SinH(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Sqr",
        category: "math",
        signature: "Sqr(x)",
        summary_ru: "Возвращает квадрат числа x, сохраняя тип (целое для Int, дробное для Float).",
        summary_en: "Returns the square of x, preserving its type (Int stays Int, Float stays Float).",
        example: "Sqr(4)",
        note_ru: "Ошибка переполнения i128 при целочисленном аргументе.",
        note_en: "Overflow error with an integer argument that exceeds i128.",
    },
    HelpEntry {
        name: "Sqrt",
        category: "math",
        signature: "Sqrt(x)",
        summary_ru: "Возвращает квадратный корень x как число с плавающей точкой.",
        summary_en: "Returns the square root of x as a float.",
        example: "Sqrt(2)",
        note_ru: "Для x<0 результат NaN.",
        note_en: "Returns NaN for x<0.",
    },
    HelpEntry {
        name: "StrToFile",
        category: "fileio",
        signature: "StrToFile(path, data)",
        summary_ru: "Записывает строку data в файл path (перезаписывая его) и возвращает записанную строку.",
        summary_en: "Writes string data to file path (overwriting it) and returns the written string.",
        example: "StrToFile(\"out.txt\", \"hello\")",
        note_ru: "Обращается к файловой системе; перезаписывает файл; ошибка ввода-вывода при недоступности пути.",
        note_en: "Touches the filesystem; overwrites the file; I/O error if the path is not writable.",
    },
    HelpEntry {
        name: "Tan",
        category: "trig",
        signature: "Tan(x)",
        summary_ru: "Возвращает тангенс угла x, заданного в радианах.",
        summary_en: "Returns the tangent of angle x given in radians.",
        example: "Tan(0)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "TanH",
        category: "trig",
        signature: "TanH(x)",
        summary_ru: "Возвращает гиперболический тангенс x.",
        summary_en: "Returns the hyperbolic tangent of x.",
        example: "TanH(1)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Tiger",
        category: "hash",
        signature: "Tiger(s)",
        summary_ru: "Возвращает Tiger-хеш строки в виде hex-строки.",
        summary_en: "Returns the Tiger hash of a string as a hex string.",
        example: "Tiger(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Trim",
        category: "strings",
        signature: "Trim(s)",
        summary_ru: "Возвращает s с удалёнными пробельными символами в начале и в конце.",
        summary_en: "Returns s with leading and trailing whitespace removed.",
        example: "Trim(\"  hi  \")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "TrimLeft",
        category: "strings",
        signature: "TrimLeft(s)",
        summary_ru: "Возвращает s с удалёнными пробельными символами в начале.",
        summary_en: "Returns s with leading whitespace removed.",
        example: "TrimLeft(\"  hi  \")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "TrimRight",
        category: "strings",
        signature: "TrimRight(s)",
        summary_ru: "Возвращает s с удалёнными пробельными символами в конце.",
        summary_en: "Returns s with trailing whitespace removed.",
        example: "TrimRight(\"  hi  \")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Trunc",
        category: "math",
        signature: "Trunc(x)",
        summary_ru: "Отбрасывает дробную часть x, возвращая целое в сторону нуля.",
        summary_en: "Truncates x toward zero, returning an integer.",
        example: "Trunc(2.9)",
        note_ru: "Ошибка, если результат выходит за пределы i128.",
        note_en: "Errors if the result falls outside the i128 range.",
    },
    HelpEntry {
        name: "Upper",
        category: "strings",
        signature: "Upper(s)",
        summary_ru: "Возвращает строку s, приведённую к верхнему регистру.",
        summary_en: "Returns string s converted to uppercase.",
        example: "Upper(\"abc\")",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "Xor",
        category: "logic",
        signature: "Xor(a, b)",
        summary_ru: "Возвращает побитовое исключающее ИЛИ двух целых чисел.",
        summary_en: "Returns the bitwise XOR of two integers.",
        example: "Xor(12, 10)",
        note_ru: "",
        note_en: "",
    },
    HelpEntry {
        name: "print",
        category: "io",
        signature: "print(x1, x2, ...)",
        summary_ru: "Выводит аргументы, разделённые пробелом, в буфер вывода и возвращает первый аргумент.",
        summary_en: "Prints the arguments separated by spaces to the output buffer and returns the first argument.",
        example: "print(\"result:\", 42)",
        note_ru: "Не входит в реестр функций (спецобработка); требует минимум 1 аргумент; может быть переопределён пользовательской функцией.",
        note_en: "Not part of the function registry (special-cased); requires at least 1 argument; can be shadowed by a user-defined function.",
    },
];
